Chore: implement `Clone & Copy` common traits
ratatui-org/ratatui pull request #350
Opened 2023-07-27 05:32 UTC by TieWay59

Implement `Clone & Copy` common traits for most structs in src.

Only implement `Copy` for structs that are simple and trivial to copy.

Reorder the derive fields to be more consistent:

    Debug, Default, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash

see: https://github.com/ratatui-org/ratatui/issues/307

2023-07-27 23:46 UTC, joshka requested changes
LGTM with the changes that @mindoodoo mentioned

2023-07-28 06:59 UTC, mindoodoo approved these changes

2023-07-28 11:02 UTC, joshka approved these changes

2023-07-28 11:04 UTC, merged

2023-07-28 11:12 UTC, joshka commented
Thanks again for the great effort on this!