chore: Check that PR title matches conventional commit guidelines
ratatui-org/ratatui pull request #459
Opened 2023-09-01 14:22 UTC by kdheepak

This runs a quick check to see if the PR title matches conventions commit guidelines. This action reruns if the title is edited and modified.

2023-09-01 15:02 UTC, a-kenji commented
I assumed the `committed` check does that already. Is that incorrect?

2023-09-01 15:05 UTC, mindoodoo approved these changes
@a-kenji Unfortunately not :/

Thanks kd !

2023-09-01 22:30 UTC, joshka requested changes

2023-09-01 22:30 UTC, joshka commented on .github/workflows/check-pr-title.yml
> +        if ! echo "$title" | grep -qE '^(build|chore|ci|docs|style|refactor|perf|test|feat|fix): '; then
```suggestion
        if ! echo "$title" | grep -qE '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?!?: '; then
```
Adds:
- `revert` (from committed.toml)
- optional scope: `(scope)`
- optional `!` to indicate breaking changes

2023-09-02 00:47 UTC, joshka approved these changes

2023-09-02 00:48 UTC, joshka commented
Let's squash this and then merge.

2023-09-02 02:56 UTC, merged