docs(paragraph): added documentation to the "alignment" method
ratatui-org/ratatui pull request #467
Opened 2023-09-04 22:03 UTC by DreadedHippy

Added documentation to the `alignment` method of the `Paragraph` widget.

This is really just 1 commit, the second commit was made because the first wasn't signed

2023-09-04 22:24 UTC, joshka requested changes
To fix this up rather than creating a new PR, you can rebase and squash the commits:
```
git rebase -i
change the second "pick" to "fixup" (or just "f"), save and close
git push origin main
```

2023-09-04 22:24 UTC, joshka commented on src/widgets/paragraph.rs
> +    /// # use ratatui::layout::Alignment;
This is included in the `prelude::*` import, so isn't necessary.
```suggestion
```

2023-09-04 22:24 UTC, joshka commented on src/widgets/paragraph.rs
> +    ///
There's a extra space at the end of this line and the other empty line below that rustfmt will delete.
```suggestion
    ///
```
run the formatter locally using:
```shell
cargo +nightly fmt --all
```

2023-09-04 22:24 UTC, joshka commented on src/widgets/paragraph.rs
> +    ///
```suggestion
    ///
```

2023-09-04 23:13 UTC, DreadedHippy commented
I've resolved all suggested changes.

Although the following error kept popping up:
```

error[E0432]: unresolved import `sys`
  --> C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\termion-2.0.1\src\raw.rs:29:5
   |
29 | use sys::Termios;
   |     ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate
```

I pushed with the '--no-verify' flag

2023-09-05 05:31 UTC, joshka approved these changes

2023-09-05 05:35 UTC, closed without merging

2023-09-05 05:45 UTC, joshka commented
Apologies - I just accidentally pushed the main branch over your main branch rather than my local copy of your main branch rebased to your main branch (which closes the PR and locks me out of the branch), so this shows as closed. I've merged it out of band to fix things up however).

Thanks for your first contribution to ratatui!

2023-09-05 07:21 UTC, DreadedHippy commented
Ayyyyy! 🚀🚀🚀🚀🚀