feat(table): Add a Table::segment_size method
ratatui-org/ratatui pull request #660
Opened 2023-12-03 19:05 UTC by asomers

It works just like Layout::segment_size, but for Tables.  Previously, it was impossible to distribute extra space anywhere in a Table.

Fixes #370

2023-12-03 23:59 UTC, joshka requested changes
LGTM - 1 small nit.

Can you please update the commit message (or provide one in a comment) that describes the behavior directly rather than in reference to `Layout`. This will end up in the Changelog, so think about how you'd announce the functionality rather than just describing the change and perhaps add 3 small code examples like

```rust
let area = Rect::new(0, 0, 62, 1);
let widths = [Min(10), Min(10, Min(10)];
// results in column widths 10, 10, 10
Table::new(rows).widths(widths).segment_size(SegmentSize::None);
// ...
```

2023-12-03 23:59 UTC, joshka commented on src/widgets/table.rs
> +    segment_size: SegmentSize,
Nit: Add a comment here

2023-12-03 23:59 UTC, joshka commented on src/widgets/table.rs
> +    /// space to the last column or to distribute it equally.
Add examples something like...

```rust
let area = Rect::new(0, 0, 62, 1);
let widths = [Min(10), Min(10, Min(10)];
// results in column widths 10, 10, 10
Table::new(rows).widths(widths).segment_size(SegmentSize::None);
// ...
```

2023-12-04 18:48 UTC, asomers commented
Does your CI process merge PRs with the main branch before running tests?  Because the test that's failing is one that isn't in my branch.  Neat, if true.

2023-12-04 18:49 UTC, joshka commented
> Does your CI process merge PRs with the main branch before running tests? Because the test that's failing is one that isn't in my branch. Neat, if true.

Yep :)
If it was the tabs - I just fixed that issue, so if you rebase it should be fine

2023-12-04 18:57 UTC, asomers commented
Rebased.  And I squashed my commits to satisfy the commit style checker.

2023-12-04 19:09 UTC, orhun approved these changes

2023-12-04 21:50 UTC, joshka approved these changes

2023-12-04 21:51 UTC, merged