Render line info methods on paragraph
ratatui-org/ratatui pull request #668
Opened 2023-12-05 20:18 UTC by TylerBloom

This PR adds two methods to the `Paragraph` widget to help get information about the rendered paragraph. The first method, `Paragraph::line_count`, takes a bounding width and returns the number of lines necessary to display the full paragraph when rendered. My motivation for this method is to use it with scrollbars. If a paragraph has wrapped text, it is currently impossible to get the number of lines it will need.

The second method is a natural extension of this, `Paragraph::line_width`. This returns the smallest line width needed to fully display every line of a paragraph. This is simply the maximum line widths. Together, these two methods can be used to calculate the minimum bounding box for a paragraph.

2023-12-05 20:29 UTC, joshka commented
Nice. I think this probably is a good interim approach to getting info about wrapping until we handle it properly in Line and Text.

2023-12-05 23:08 UTC, joshka requested changes
LGTM generally. Needs a couple of extra tests and there's a couple of small nits.

I'm not sure whether we should put this behind an unstable flag (because of https://github.com/ratatui-org/ratatui/issues/293) or whether it should just be something that hangs around forever. What do the other @ratatui-org/core maintainers think about this?

2023-12-05 23:08 UTC, joshka commented on src/widgets/paragraph.rs
> +            .max_by(|a, b| a.cmp(b))
nit: can this be `.max()`?

2023-12-05 23:08 UTC, joshka commented on tests/widgets_paragraph.rs
> +fn widgets_paragraph_counts_rendered_lines() {
can you please add some tests for the lines that codecov annotates as not covered (width < 1, no wrap and line_width function)

2023-12-06 09:59 UTC, Valentin271 commented
> put this behind an unstable flag (because of https://github.com/ratatui-org/ratatui/issues/293)

Yep definitely agree with that. We should sort out text wrapping pretty soon as I feel it's one of the most requested feature.

Otherwise we'd probably have to remove it at some point with a breaking change.

This unstable feature idea could also be useful to test designs and new APIs.

2023-12-06 10:35 UTC, kdheepak commented
I like the feature! It's a particularly useful building block for making a feature like "jump to $N line" or similar features. I haven't had a chance to review the code yet, but in favor of tagging it as unstable.

2023-12-06 10:42 UTC, joshka commented
Cool - Sounds like stability is the go - see `layout::SegmentSize` for an example of how to tag it.

2023-12-07 02:08 UTC, joshka approved these changes

2023-12-07 15:21 UTC, Valentin271 commented
Ok so looks like you're just missing a rebase on main then @TylerBloom

2023-12-07 17:13 UTC, Valentin271 approved these changes
Looks good, thanks for your contribution!

2023-12-07 17:14 UTC, merged

2023-12-07 17:35 UTC, orhun commented
Too late to review but definitely a +1 from me. Thanks!