feat(rect.rs): implement Rows and Columns iterators in Rect
ratatui-org/ratatui pull request #765
Opened 2024-01-07 20:02 UTC by BogdanPaul15

Signed-off-by: Prisacaru Bogdan-Paul <paulbp68@gmail.com>

#752

2024-01-07 21:31 UTC, Valentin271 reviewed
I'm not sure this is what joshka meant when creating the issue.

I think you wanted to do the following right?
```diff
- for x in area.left()..area.right() { 
+ for x in area.columns() { 
-   for y in area.top()..area.bottom() { 
+   for y in area.rows() { 
    buf.get_mut(x, y).reset(); 
  } 
} 
```

The way I understood the issue, the iterators were supposed to return `Rect`s representing the rows and column. So we could work on that and, for example, get the columns of a row (so a `Rect`).

```rust
let area = Rect(0, 0, 10, 5);
for row in area.rows() {
  // row is Rect { x: 0, y: 0, width: 10, height: 1}, note height of one because it's a row
  // on second iteration this will become Rect { x: 0, y: 1, width: 10, height: 1}
  // up to Rect { x: 0, y: 9, width: 10, height: 1}, y of 9 because there is 10 rows starting from 0

  // and then here because row is a `Rect` we can call `columns` again
  for cell in row.columns() {
    // which will give Rect { x: 0, y: 0, width: 1, height: 1}, width is one because it's a columns, height is one because we iterate over a row
    // then Rect { x: 1, y: 0, width: 1, height: 1}, incrementing x up to 9
    // and at the end Rect { x: 9, y: 9, width: 1, height: 1}, the last cell on the bottom right

    // here we can call rect.x and rect.y because the resulting rect, when iterating over rows and columns, is 1 by 1, so a cell
    buf.get_mut(cell.x, cell.y).reset();
  }
}
```

That was my understanding, let's wait for @joshka's input

2024-01-07 22:17 UTC, BogdanPaul15 commented
I understand your point. I will wait for @joshka. Thank you!

2024-01-07 23:45 UTC, joshka requested changes
@Valentin271 was right. I'd expect each element of the iterator to be a single height or single width Rect.

For the tests, simplify them to compare rows().collect() to a hard coded vec of rects. This will visually show that the x or y index is changing, but the width or height is always 1.

2024-01-08 10:30 UTC, BogdanPaul15 commented
From my understanding, this is what you needed. Please let me know if I am wrong.

2024-01-08 10:55 UTC, Valentin271 requested changes
Other than my few comments looks good.

2024-01-08 10:55 UTC, Valentin271 commented on src/layout/rect.rs
> +    pub current_column: u16,
You don't need the current column in the row iterator.

2024-01-08 10:55 UTC, Valentin271 commented on src/layout/rect.rs
> +    pub current_row: u16,
Same here you don't need the current_row in the columns iterator.

2024-01-08 10:55 UTC, Valentin271 commented on src/layout/rect.rs
> +        if self.current_row >= self.rect.y + self.rect.height {
You can use `Rect::bottom()` here to make this easier to maintain and avoid panics.
```suggestion
        if self.current_row >= self.rect.bottom() {
```

2024-01-08 10:55 UTC, Valentin271 commented on src/layout/rect.rs
> +        if self.current_column >= self.rect.x + self.rect.width {
Similarly, you can use `Rect::right()` here.
```suggestion
        if self.current_column >= self.rect.right() {
```

2024-01-08 11:04 UTC, Valentin271 commented
It looks like you tried to sign your commit (as shows the PR description), but the github interface doesn't show it, could check that?

You have some information here https://github.com/ratatui-org/ratatui/blob/main/CONTRIBUTING.md#sign-your-commits.

If you need help feel free to ask.

2024-01-08 11:06 UTC, BogdanPaul15 commented
@Valentin271 thank you for your feedback. Should I commit these changes? Also, yes, I've tried to sign my commits, my machine is already configured with gpg keys, but I don't know why it doesn't work.

2024-01-08 11:24 UTC, Valentin271 commented
Have you looked at https://commitizen-tools.github.io/commitizen/getting_started/#sign-off-the-commit? (weird though I don't remember having to do that when I used it)

You can either commit the proposed changes from the interface (will be committed as me though) or commit them yourself as usual, as you wish.

2024-01-08 11:49 UTC, Valentin271 approved these changes
Looks all good, code and signing. Thanks!

I'll wait for a second approval on this.

2024-01-08 11:56 UTC, joshka approved these changes
Looks great.

2024-01-08 11:59 UTC, joshka commented
To get this to merge, all the commits need to be signed, not just the last one. Can you please squash the commits locally into a single commit and force push to your branch?

<img width="952" alt="image" src="https://github.com/ratatui-org/ratatui/assets/381361/06dc2c32-894e-4002-9b21-cf81169951bc">

Thanks for the PR :)

2024-01-08 12:22 UTC, BogdanPaul15 commented
Ok, I'm trying to squash into a single commit and force push.

2024-01-08 13:41 UTC, BogdanPaul15 commented
I need some help. When I try to squash my commits, I am getting others commits than mine. Do I have to squash them too?

2024-01-08 14:31 UTC, Valentin271 commented
I'd suggest

```sh
// this will go back to your latest relevant commit
git reset --hard d9195580cc9eb2c941f66e34bb4630eee33d14c3

git rebase -i HEAD~4
// replace pick with squash for the last 3 commits, see attached screenshot 
// then the commit message will show up, edit as needed

// just to save the changes
git push -f --no-verify
```

Then sign your commit and force push.
If you can't/don't know how to sign an already existing commit, you can

```sh
// deletes the commit and put the changes back to staged
git reset --soft HEAD^
// then commit+sign as usual
// and force push
git push -f --no-verify
```

Might not be the most straightforward way but at least it should work.

---

`rebase -i` interface
![image](https://github.com/ratatui-org/ratatui/assets/36198422/d1d9c25b-39ba-4790-944e-775bcc9e143f)

2024-01-08 14:47 UTC, BogdanPaul15 commented
Thank you. I really don't lnow why this failed.

2024-01-08 14:49 UTC, Valentin271 commented
You're welcome, and thanks for your contribution!

2024-01-08 14:51 UTC, merged