feat(layout): add Position struct
ratatui-org/ratatui pull request #790
Opened 2024-01-11 16:51 UTC by joshka

This stores the x and y coordinates (columns and rows)

- add conversions from Rect
- add conversion with Size to Rect
- add Rect::as_position

2024-01-11 18:26 UTC, Valentin271 requested changes

2024-01-11 18:26 UTC, Valentin271 commented on src/layout/position.rs
> +pub struct Position {
Could you add the derive macros here

2024-01-11 18:28 UTC, Valentin271 commented
Could you also add a test for `From<(Position, size)> for Rect`? (don't forget to fix formatting)

2024-01-11 18:31 UTC, Valentin271 commented
Check out https://github.com/ratatui-org/ratatui/pull/789#issuecomment-1887535265.

Mainly this allows easy manipulation and especially storage of positions.

2024-01-18 10:39 UTC, joshka commented
One place I'd like this is instead of a (u16,u16) tuple in a state object

2024-01-18 10:48 UTC, joshka commented
realized I pushed, but didn't see that it failed due to the a missing import in a doc test. Pushed now

2024-01-18 11:22 UTC, Valentin271 commented
It seems like the doc-tests are still failing due to missing import @joshka.

2024-01-18 13:00 UTC, joshka commented
> It seems like the doc-tests are still failing due to missing import @joshka.

Missed the commit. Fixed now.

2024-01-18 13:06 UTC, Valentin271 approved these changes

2024-01-18 13:07 UTC, merged